version: "3.7"

services:
  trade2:
    container_name: trade2
    image: puyuantech/fof:latest
    tty: true
    stdin_open: true
    network_mode: fof-swarm
    volumes:
      - ./shared/etc/basic_config.json:/shared/etc/basic_config.json
      - /data/fof_current/log/:/shared/log
      - /data/fof_current/key/:/shared/key
    command: >
      bash -c " cp /shared/etc/basic_config.json /shared/etc/config.json &&
                gun env register --init --docker_container &&
                gun run tr -f trade2"
