version: "3.7"

services:
  trade4:
    container_name: trade4
    image: puyuantech/fof:latest
    tty: true
    stdin_open: true
    network_mode: fof-swarm
    volumes:
      - ./shared/etc/trade4.json:/shared/etc/config.json
      - /data/fof_current/log/:/shared/log
      - /data/fof_current/key/:/shared/key
    command: >
      bash -c " cp /shared/etc/basic_config.json /shared/etc/config.json &&
                gun env register --init --docker_container &&
                gun run tr -f trade4"

  trade5:
    container_name: trade5
    image: puyuantech/fof:latest
    tty: true
    stdin_open: true
    network_mode: fof-swarm
    volumes:
      - ./shared/etc/trade5.json:/shared/etc/config.json
      - /data/fof_current/log/:/shared/log
      - /data/fof_current/key/:/shared/key
    command: >
      bash -c " cp /shared/etc/basic_config.json /shared/etc/config.json &&
                gun env register --init --docker_container &&
                gun run tr -f trade5"

  trade6:
    container_name: trade6
    image: puyuantech/fof:latest
    tty: true
    stdin_open: true
    network_mode: fof-swarm
    volumes:
      - ./shared/etc/trade6.json:/shared/etc/config.json
      - /data/fof_current/log/:/shared/log
      - /data/fof_current/key/:/shared/key
    command: >
      bash -c " cp /shared/etc/basic_config.json /shared/etc/config.json &&
                gun env register --init --docker_container &&
                gun run tr -f trade6"
