version: "3.7"

services:
  trade1:
    container_name: trade1
    image: puyuantech/fof:latest
    tty: true
    stdin_open: true
    network_mode: fof-swarm
    depends_on:
      - master
    volumes:
      - ./shared/etc/basic_config.json:/shared/etc/basic_config.json
      - /data/fof_current/log/:/shared/log
    command: >
      bash -c " cp /shared/etc/basic_config.json /shared/etc/config.json &&
                gun env register --init --docker_container &&
                gun run tr -f trade1"
